### ISSUE TITLE
Occasional k-means IndexError

### ISSUE THREAD

**Issue by rluedde** [rluedde/ml_algorithms#4]
Most of the time the classification doesn't throw an error but sometimes (seemingly randomly) it does. The error is this:

```Traceback (most recent call last):
  File "run_k_means_clustering.py", line 15, in <module>
    class_df = km.classify()
  File ".../k_means_clustering/k_means_clustering.py", line 58, in classify
    self.distances[i, k] = distance.euclidean(self.features[i], centers[k])
IndexError: index 2 is out of bounds for axis 0 with size 2
```

The problem isn't more prevalent on smaller datasets. I originally thought that this might be a case of picking the last point as a random starting place and then that last point's index doesn't exist somewhere. If this was the case, this problem would come up far more frequently on smaller datasets but it doesn't. No idea what's happening here.

**Comment by rluedde** [comment]
The problem occurs when sometimes there are only k-1 cluster centers when there should be k centers, always.
